### ISSUE TITLE
question parallel child nodes

### ISSUE THREAD

**Issue by elsuper-josev** [kuria/dom#1]
Hello,
great job you did.

I'm trying to figure how traverse child nodes.

Imagine need to retrieve:
$items = $dom->query('//ol[@id="results"]/li[@class="algo"]//h2/a');
and also
$items = $dom->query('//ol[@id="results"]/li[@class="algo"]div[@class="caption"]/p');

As you can see both data are child of 'algo' class.

From /h2/a/ I will get href and textContent.

From caption/p I'll get textContent, some kind of description.

I need to run through those $items from the same foreach because not all nodes has a description.

Thanks for your help.
Jose

**Comment by ShiraNai7** [comment]
You can query the list elements first and then query their child nodes using the current list element as a context node:

```php
foreach ($dom->query('//ol[@id="results"]/li[@Class="algo"]') as $algo) {
    $link = $dom->queryOne('.//h2/a', $algo);
    $caption = $dom->queryOne('.//div[@Class="caption"]/p', $algo);

    // do something with $link and $caption nodes, if they are not NULL...
}
```

See PHP docs for more info about context nodes: http://php.net/manual/en/domxpath.query.php#refsect1-domxpath.query-parameters

**Comment by shira-374** [comment]
Hello. You can query the list elements first and then query their child nodes using the current list element as a context node:

```php
foreach ($dom->query('//ol[@id="results"]/li[@Class="algo"]') as $algo) {
    $link = $dom->queryOne('.//h2/a', $algo);
    $caption = $dom->queryOne('.//div[@Class="caption"]/p', $algo);

    // do something with $link and $caption nodes, if they are not NULL...
}
```

See PHP docs for more info about context nodes: http://php.net/manual/en/domxpath.query.php#refsect1-domxpath.query-parameters

**Comment by elsuper-josev** [comment]
Thanks for your help. I will follow your example.
